### ISSUE TITLE
Thanks for your usage of our PyPop7. We have included your interesting work in https://pypop.readthedocs.io/en/latest/applications.html

### ISSUE THREAD

**Issue by Evolutionary-Intelligence** [BruthYU/BPT-VLM#1]
Thanks for your usage of our PyPop7.

We have included your interesting work in https://pypop.readthedocs.io/en/latest/applications.html

**Comment by BruthYU** [comment]
> Thanks for your usage of our PyPop7.
> 
> We have included your interesting work in https://pypop.readthedocs.io/en/latest/applications.html

Thanks for your attention, I'm now in Macau attending the IJCAI conference, when the paper is officially published, you can also include it, and we will add an acknowledgement for Pypop7 in our project.

**Comment by Evolutionary-Intelligence** [comment]
OK. We will add your **interesting** paper in our website: https://pypop.readthedocs.io/en/latest/applications.html. Thanks for your usage again!
